language: node_js

node_js:
  - 10

install:
  - npm install
  - npm run build

script:
  - npm test

notifications:
  email:
    on_failure: change

cache:
  npm: true
  directories:
    - node_modules

