const DEBUG_SHOW_DEBUG_INFORMATION_KEY = 'showSessionDebugViews';
const DEBUG_SHOW_PAGE_CONTAINER_KEY = 'showLegacyPageContainerDebugColor';
const POST_LOGIN_REDIRECT_LOCATION_KEY = 'post-login-redirect-location';
const PRIVACY_PREFERENCES_KEY = 'privacy_preferences_v2';
const SESSION_COOKIE_KEY = 'session_v2';
const COOKIE_EXPIRY_TIME = 24 * 60 * 60 * 100 * 1000; // 100 days

export {
  DEBUG_SHOW_DEBUG_INFORMATION_KEY,
  DEBUG_SHOW_PAGE_CONTAINER_KEY,
  POST_LOGIN_REDIRECT_LOCATION_KEY,
  PRIVACY_PREFERENCES_KEY,
  SESSION_COOKIE_KEY,
  COOKIE_EXPIRY_TIME,
};
export default {
  DEBUG_SHOW_DEBUG_INFORMATION_KEY,
  DEBUG_SHOW_PAGE_CONTAINER_KEY,
  POST_LOGIN_REDIRECT_LOCATION_KEY,
  PRIVACY_PREFERENCES_KEY,
  SESSION_COOKIE_KEY,
  COOKIE_EXPIRY_TIME,
};
