export const KEY = 'consent';
export const CONSENT = `app/${KEY}/CONSENT`;
export const DEFER_CONSENT = `app/${KEY}/DEFER_CONSENT`;
export const SET_CONSENT_REASON = `app/${KEY}/SET_CONSENT_REASON`;
export const RESET_CONSENT = `app/${KEY}/RESET_CONSENT`;

export const CONSENT_STATE_UNSET = 'CONSENT_STATE_UNSET';
export const CONSENT_STATE_ALLOWED = 'CONSENT_STATE_ALLOWED';
export const CONSENT_STATE_DEFERRED = 'CONSENT_STATE_DEFERRED';

export const CONSENT_STATE_ALLOWED_CLIENT_VALUE = 'CONSENT_ALLOWED';
export const CONSENT_STATE_DEFERRED_CLIENT_VALUE = 'CONSENT_DEFERRED';
