name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci

      - name: lint
        run: npm run lint

      - name: jest test
        run: npm test

  snapshot-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: run snapshot tests
        run: |
          ./scripts/docker/prepare.sh
          ./scripts/docker/run-tests.sh

      - name: save snapshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: bitmaps_reference
          path: backstop_data/bitmaps_reference

  deploy:
    runs-on: ubuntu-latest
    needs: [test, snapshot-test]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci

      - name: build
        run: npm run build

      - name: deploy
        run: |
          zip -r build build
          echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
          chmod 400 ./identityFile.txt
          scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./build.zip ubuntu@ec2-35-178-235-11.eu-west-2.compute.amazonaws.com:/home/ubuntu/screen-reader-adventures/
